### ISSUE TITLE
Move this repo to https://github.com/jakartaee

### ISSUE THREAD

**Issue by joakime** [jakartaee/pages#222]
_Messages seen in other eclipse-ee4j project issues from @arjantijms_ 

> In the steering committee we voted to moved all specification projects from eclipse-ee4j to jakartaee. As such this repo should move to in due time.
>
> Moving is fairly automatic, and redirects will be automatically put in place from the current location here to the new location.

I think this is a good opportunity to also get the name changed from "JSP" to "Jakarta Pages" based on past discussions about the problems with the "JSP" moniker.

Probably something like ... https://github.com/jakartaee/pages

**Comment by arjantijms** [comment]
The repo has been moved to the suggested location.

**Comment by joakime** [comment]
Woah, that was smooth, I didn't even notice the change.
Closing ...
