### ISSUE TITLE
Finalize Jakarta Pages 3.1

### ISSUE THREAD

**Issue by keilw** [jakartaee/pages#230]
- [X] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
API jar now available: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/servlet/jsp/jakarta.servlet.jsp-api/3.1.0/

**Comment by markt-asf** [comment]
No XML schemas, no need to merge release branch.
Confirmed the staged repo has been replicated to Maven Central.
Just need to check the website links.

**Comment by markt-asf** [comment]
Links all look good.
No strictly on the checklist but I want to bump the version number before closing this.

**Comment by arjantijms** [comment]
Sounds good, thanks!

**Comment by markt-asf** [comment]
All done.
