### ISSUE TITLE
Missing static imports with Expression Language expressions

### ISSUE THREAD

**Issue by isaacrivriv** [jakartaee/pages#239]
With the changes made for pages 3.1 making the imports in a jsp available to the EL scripting language, ran the following jsp to verify static imports 
```jsp
<%@ page import = "static myapp.Example.STATIC_VAR, static myapp.Example.STATIC_METHOD" %>
<html>
   <head>
      <title>Import Static</title>
   </head>
   
   <body>
      EL expressions: <br/>
      ${STATIC_VAR}
      ${STATIC_METHOD()}

      <br/>
      <br/>
      
      JSP expressions: <br/>
      <%=STATIC_VAR%>
      <%=STATIC_METHOD()%>
   </body>
</html>
```

The JSP expressions resolve as expected but of the EL expressions, only STATIC_METHOD() works. Using the Tomcat JSP API all expressions resolve as expected.

See also Tomcat issue https://bz.apache.org/bugzilla/show_bug.cgi?id=66441

**Comment by joakime** [comment]
This might belong to the EL Spec project -> https://github.com/jakartaee/expression-language
