### ISSUE TITLE
Server Pages 4.0.0 - Tomcat 11.0.0-M19-SNAPSHOT certification request

### ISSUE THREAD

**Issue by markt-asf** [jakartaee/pages#265]
TCK Certification Summary
=========================

License:
  The terms of the EFTL are acceptable.

Product Name, Version and download URL:
  Apache Tomcat
  11.0.0-M19-SNAPSHOT (build 20240329.113130-29)
  https://repository.apache.org/content/groups/snapshots/org/apache/tomcat/tomcat/11.0.0-M19-SNAPSHOT/tomcat-11.0.0-M19-20240329.113130-29.tar.gz

Specification Name, Version and download URL:
  Jakarta Server Pages
  4.0.0
  https://github.com/jakartaee/specifications/pull/723

TCK Version, digital SHA-256 fingerprint and download URL
  TCK
  4.0.0
  https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-pages-tck-4.0.0.zip
  SHA512: 229b2a89481925537b3ad81f9fb9aa6f0f571937cb831232317c902bd83f861d0427ad6a7a0ed6477ff67f0f41520904d8b6c5b4c4c6fc6bf68759e2407121e3

Implementation runtime Version(s) tested:
  Apache Tomcat
  11.0.0-M19-SNAPSHOT (build 20240329.113130-29)

Public URL of TCK Results Summary:
  https://tomcat.apache.org/tck/jsp-4.0.0-tomcat-11.0.0-M19-SNAPSHOT.txt

Any Additional Specification Certification Requirements:
  None

Java runtime used to run the implementation:
  Java 17 - Temurin 17.0.10
  Java 21 - Temurin 21.0.2

Summary of the information for the certification environment:
  Ubuntu 22.04.4 LTS
​  https://github.com/apache/tomcat-tck
  hash 71ebd556b0122a8016f3c76e78e5005e61ff91cb

A statement attesting that all TCK requirements have been met, including any compatibility rules:
  Confirmed

Test results:
  Java 17: Tests run: 700, Failures: 0, Errors: 0, Skipped: 0
  Java 21: Tests run: 700, Failures: 0, Errors: 0, Skipped: 0

**Comment by alwin-joseph** [comment]
Please update the TCK SHA as it was restaged after removing the SNAPSHOT dependencies.

**Comment by markt-asf** [comment]
Withdrawn as the TCK was updated. Since we have to update this might as well use a released Tomcat version rather than a snaphot.
